### ISSUE TITLE
sign some user action requests using user access token

### ISSUE THREAD

**Issue by lokune** [Ma3Route/node-sdk#10]
Add the capability to sign requests using user accesstoken. Such requests include deletion, favoriting etc.

**Comment by GochoMugo** [comment]
All requests (both `GET` and `POST`) are signed using the secret key.

* https://github.com/Ma3Route/node-sdk/blob/master/lib/generate.js#L57
* https://github.com/Ma3Route/node-sdk/blob/master/lib/generate.js#L112
* https://github.com/Ma3Route/node-sdk/blob/master/lib/generate.js#L162

**Comment by lokune** [comment]
I get that. I meant user access token. Each user has an access token and this should be used to sign certain user-centric requests. i.e, instead of the app secret key, the user access token will be used to sign those requests, to authenticate them.

**Comment by GochoMugo** [comment]
If the secret and key are passed as parameters to any request, they will be used to sign the single request.

See https://github.com/Ma3Route/node-sdk/blob/master/lib/generate.js#L49

**Comment by GochoMugo** [comment]
This feature will be documented later.
