### ISSUE TITLE
Body and Query Parameters

### ISSUE THREAD

**Issue by lokune** [Ma3Route/node-sdk#7]
Let these be determined by the client making the request. When a client sends the request object or query string, use the parameters to generate signature etc. Do not restrict to what is defined in **params.json**, this will be very difficult to maintain especially when the Ma3Route REST API keeps changing.

**Comment by GochoMugo** [comment]
**FIXED IN v0.8.0**

The SDK defaults the settings `enforce_params_filter` to `false`. This fixes this issue as it now passes all parameters to API endpoint.
