### ISSUE TITLE
Rename places module to geo

### ISSUE THREAD

**Issue by GochoMugo** [Ma3Route/node-sdk#8]
Currently, the SDK exports an inner module, named `places`. Would it be more clearer to rename it to `geo` to inform users that is handles geographical requests.

**/cc** @lokune

**Comment by lokune** [comment]
Places is appropriate. Means the places like Ngara, Survey etc (most of them are road sections). Geo would still work but I think places is more descriptive.

**Comment by GochoMugo** [comment]
It shall remain `places`!
